=== rizkyghani16/XSD/pendidikan.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="pendidikan">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element ref="alamat"/>
                <xs:element ref="email"/>
                <xs:element ref="jeniskelamin"/>
                <xs:element ref="jurusan"/>
                <xs:element ref="kampus"/>
                <xs:element ref="kelas"/>
                <xs:element ref="nama"/>
                <xs:element ref="npm"/>
                <xs:element ref="prodi"/>
            </xs:choice>
            <xs:attribute name="Data" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="email">
    	<xs:simpleType>
    		<xs:restriction base="xs:string">
    			<xs:pattern
    				value="([0-9a-zA-Z]([-.\w]*[0-9a-zA-Z])*@([0-9a-zA-Z][-\w]*[0-9a-zA-Z]\.)+[a-zA-Z]{2,9})">
    			</xs:pattern>
    		</xs:restriction>
    	</xs:simpleType>
    </xs:element>
    <xs:element name="jeniskelamin" type="xs:NCName"/>
    <xs:element name="jurusan" type="xs:string"/>
    <xs:element name="kampus">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="alamat"/>
            </xs:sequence>
            <xs:attribute name="nama" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="kelas" type="xs:NMTOKEN"/>
    <xs:element name="nama" type="xs:string"/>
    <xs:element name="npm" type="xs:integer"/>
    <xs:element name="prodi" type="xs:string"/>
    <xs:element name="alamat" type="xs:string"/>
</xs:schema>

=== rizkyghani16/XSD/Pendidikan.xml
<?xml version="1.0" encoding="UTF-8"?>
<pendidikan Data="Mahasiswa" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="pendidikan.xsd">
	
	<nama>Rizky Abdul Ghani Suherli</nama>
	<npm>1154058</npm>
	<kelas>2B</kelas>
	<prodi>Diploma 4</prodi>
	<jurusan>Teknik Informatika</jurusan>
	<jeniskelamin>Lakilaki</jeniskelamin>
	<alamat>Bandung</alamat>
	<email>rizkyghani16@gmail.com</email>
	<kampus nama="Politeknik Pos Indonesia">
		<alamat>jalan sariasih no.54 Bandung</alamat>
	</kampus>
	
	<nama>Jonathan Eka Ratmoko</nama>
	<npm>4153032</npm>
	<kelas>2B</kelas>
	<prodi>Diploma 3</prodi>
	<jurusan> Teknik Informatika</jurusan>
	<jeniskelamin>Lakilaki</jeniskelamin>
	<alamat>Jakarta</alamat>
	<email>joenathaneka@gmail.com</email>
	<kampus nama="Politeknik Pos Indonesia">
		<alamat>jalan sariasih no.54 Bandung</alamat>
	</kampus>
	
	<nama>Tri Wahyuni</nama>
	<npm>1163024</npm>
	<kelas>1C</kelas>
	<prodi>Diploma 3</prodi>
	<jurusan>Teknik Informatika</jurusan>
	<jeniskelamin>Perempuan</jeniskelamin>
	<alamat>Palembang</alamat>
	<email>tri.wahyuni2505@yahoo.com</email>
	<kampus nama="Politeknik Pos Indonesia">
		<alamat>jalan sariasih no.54 Bandung</alamat>
	</kampus>
	
	<nama>Fajri Mualim</nama>
	<npm>1154078</npm>
	<kelas>2B</kelas>
	<prodi>Diploma 4</prodi>
	<jurusan>Teknik Informatika</jurusan>
	<jeniskelamin>Lakilaki</jeniskelamin>
	<alamat>Tangerang</alamat>
	<email>fajrimualim17@gmail.com</email>
	<kampus nama="Politeknik Pos Indonesia">
		<alamat>jalan sariasih no.54 Bandung</alamat>
	</kampus>
	
	<nama>Novrianty Sagita Nawir</nama>
	<npm>4154084</npm>
	<kelas>2C</kelas>
	<prodi>Diploma 4</prodi>
	<jurusan>Manajemen Bisnis</jurusan>
	<jeniskelamin>Perempuan</jeniskelamin>
	<alamat>Pare-Pare</alamat>
	<email>novriantysagita@yahoo.co.id</email>
	<kampus nama="Politeknik Pos Indonesia">
		<alamat>jalan sariasih no.54 Bandung</alamat>
	</kampus>
</pendidikan>
